import { createFileRoute, Link } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { ChevronLeft, ChevronRight, Download, Filter, Search, Star } from "lucide-react";
import { AppShell, PageHeader } from "@/components/app-shell";
import { Status } from "@/components/intelligence-ui";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { ads } from "@/data/mock-data";

export const Route = createFileRoute("/anuncios")({head:()=>({meta:[{title:"Anúncios — Ad Intelligence"},{name:"description",content:"Explore anúncios públicos coletados e seus sinais observáveis."},{property:"og:title",content:"Anúncios — Ad Intelligence"},{property:"og:description",content:"Explore anúncios públicos coletados e seus sinais observáveis."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:AdsPage});

function AdsPage(){
 const [query,setQuery]=useState(""); const [status,setStatus]=useState("todos"); const [days,setDays]=useState("0"); const [sort,setSort]=useState("tempo"); const [page,setPage]=useState(1);
 const filtered=useMemo(()=>ads.filter(a=>(status==="todos"||(status==="ativos"?a.active:!a.active))&&a.observedDays>=Number(days)&&(a.advertiser.toLowerCase().includes(query.toLowerCase())||a.copy.toLowerCase().includes(query.toLowerCase())||a.id.includes(query))).sort((a,b)=>sort==="tempo"?b.observedDays-a.observedDays:a.advertiser.localeCompare(b.advertiser)),[query,status,days,sort]);
 const shown=filtered.slice((page-1)*6,page*6); const pages=Math.max(1,Math.ceil(filtered.length/6));
 return <AppShell><PageHeader eyebrow="Biblioteca observada" title="Anúncios" description="Conteúdo público coletado pela extensão, organizado por sinais e tempo de observação." action={<Button variant="outline"><Download/>Exportar CSV</Button>}/>
 <div className="mb-3 grid gap-2 border bg-card p-3 md:grid-cols-[1fr_150px_170px_180px_auto]"><div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} className="pl-9" placeholder="Buscar por ID, anunciante ou copy"/></div><Select value={status} onValueChange={v=>{setStatus(v);setPage(1)}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="todos">Todos os status</SelectItem><SelectItem value="ativos">Ativos</SelectItem><SelectItem value="inativos">Inativos</SelectItem></SelectContent></Select><Select value={days} onValueChange={v=>{setDays(v);setPage(1)}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{[0,3,7,14,30,60].map(v=><SelectItem key={v} value={String(v)}>{v?`${v}+ dias observados`:"Qualquer período"}</SelectItem>)}</SelectContent></Select><Select value={sort} onValueChange={setSort}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="tempo">Maior tempo observado</SelectItem><SelectItem value="anunciante">Anunciante A–Z</SelectItem></SelectContent></Select><Button variant="ghost" size="icon" title="Mais filtros"><Filter/></Button></div>
 <div className="overflow-hidden border bg-card"><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-xs"><thead className="border-b bg-muted/50 text-muted-foreground"><tr><th className="px-4 py-3">Anúncio</th><th className="px-3 py-3">Anunciante / página</th><th className="px-3 py-3">Oferta</th><th className="px-3 py-3">País</th><th className="px-3 py-3">Tempo observado</th><th className="px-3 py-3">Status</th><th className="px-4 py-3"></th></tr></thead><tbody className="divide-y">{shown.map(ad=><tr key={ad.id} className="hover:bg-muted/40"><td className="px-4 py-3"><div className="flex items-center gap-3"><img src={ad.mediaUrl} alt="Prévia do criativo" className="size-12 rounded object-cover"/><div className="max-w-[260px]"><div className="flex items-center gap-2 font-mono text-[10px] text-muted-foreground">{ad.id}{ad.favorite&&<Star className="size-3 fill-primary text-primary"/>}</div><p className="mt-1 truncate font-medium">{ad.headline??"Não disponível"}</p></div></div></td><td className="px-3 py-3"><div className="font-bold">{ad.advertiser}</div><div className="mt-1 text-muted-foreground">{ad.page}</div></td><td className="px-3 py-3"><Badge variant="secondary">{ad.category}</Badge></td><td className="px-3 py-3">{ad.country}</td><td className="px-3 py-3"><strong>{ad.observedDays} dias</strong><div className="mt-1 text-[10px] text-muted-foreground">pela nossa plataforma</div></td><td className="px-3 py-3"><Status active={ad.active}/></td><td className="px-4 py-3 text-right"><Button asChild variant="ghost" size="sm"><Link to="/anuncios/$adId" params={{adId:ad.id}}>Detalhes</Link></Button></td></tr>)}</tbody></table></div>{shown.length===0&&<div className="p-10 text-center text-sm text-muted-foreground">Nenhum anúncio encontrado.</div>}<div className="flex items-center justify-between border-t px-4 py-3 text-xs text-muted-foreground"><span>{filtered.length} anúncios encontrados</span><div className="flex items-center gap-2"><Button size="icon" variant="outline" disabled={page===1} onClick={()=>setPage(p=>p-1)}><ChevronLeft/></Button><span>Página {page} de {pages}</span><Button size="icon" variant="outline" disabled={page===pages} onClick={()=>setPage(p=>p+1)}><ChevronRight/></Button></div></div></div>
 </AppShell>;
}