import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowDown, ArrowUp, Eye, Search, Star } from "lucide-react";
import { AppShell, PageHeader } from "@/components/app-shell";
import { Score } from "@/components/intelligence-ui";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { offers } from "@/data/mock-data";

export const Route=createFileRoute("/ofertas/")({head:()=>({meta:[{title:"Ofertas — Ad Intelligence"},{name:"description",content:"Agrupamentos de ofertas com confiança e sinais observáveis."},{property:"og:title",content:"Ofertas — Ad Intelligence"},{property:"og:description",content:"Agrupamentos de ofertas com confiança e sinais observáveis."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:OffersPage});
function OffersPage(){return <AppShell><PageHeader eyebrow="Agrupamentos probabilísticos" title="Ofertas" description="Produtos e ofertas agrupados a partir de sinais observáveis, sempre acompanhados do nível de confiança."/><div className="mb-3 flex flex-col gap-2 border bg-card p-3 sm:flex-row"><div className="relative max-w-lg flex-1"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="pl-9" placeholder="Buscar produto, categoria ou anunciante"/></div><Button variant="outline">Ordenar: maior score</Button></div><div className="grid gap-3 lg:grid-cols-2">{offers.map(o=><Link key={o.id} to="/ofertas/$offerId" params={{offerId:o.id}} className="group border bg-card p-4 transition-colors hover:border-primary"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><Badge variant="secondary">{o.category}</Badge><span className="text-[10px] font-bold text-muted-foreground">Confiança {o.confidence}%</span>{o.favorite&&<Star className="size-3.5 fill-primary text-primary"/>}</div><h2 className="mt-3 font-display text-lg font-bold group-hover:text-primary">{o.product}</h2><div className="mt-1 text-xs text-muted-foreground">Faixa de preço: {o.priceRange??"Não disponível"}</div></div><Score value={o.scores.overall} label="Overall" compact/></div><div className="mt-5 grid grid-cols-3 gap-2 border-y py-3 text-xs sm:grid-cols-6"><Datum label="Anúncios" value={o.adCount}/><Datum label="Criativos" value={o.creativeCount}/><Datum label="Anunciantes" value={o.advertiserCount}/><Datum label="Páginas" value={o.landingPageCount}/><Datum label="Países" value={o.countries.length}/><Datum label="Observado" value={`${o.observedDays}d`}/></div><div className="mt-3 flex items-center justify-between text-xs"><span className={o.growth>=0?"text-positive":"text-destructive"}>{o.growth>=0?<ArrowUp className="mr-1 inline size-3"/>:<ArrowDown className="mr-1 inline size-3"/>}{Math.abs(o.growth)}% em anúncios observados</span><span className="flex items-center gap-1 font-bold text-primary"><Eye className="size-3.5"/>Ver oferta</span></div></Link>)}</div></AppShell>}
function Datum({label,value}:{label:string;value:string|number}){return <div><div className="font-display text-sm font-bold">{value}</div><div className="mt-0.5 text-[10px] text-muted-foreground">{label}</div></div>}