/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnunciosRouteImport } from './routes/anuncios'
import { Route as AnunciosAdIdRouteImport } from './routes/anuncios.$adId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnunciosRoute = AnunciosRouteImport.update({
  id: '/anuncios',
  path: '/anuncios',
  getParentRoute: () => rootRouteImport,
} as any)
const AnunciosAdIdRoute = AnunciosAdIdRouteImport.update({
  id: '/$adId',
  path: '/$adId',
  getParentRoute: () => AnunciosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anuncios': typeof AnunciosRouteWithChildren
  '/anuncios/$adId': typeof AnunciosAdIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anuncios': typeof AnunciosRouteWithChildren
  '/anuncios/$adId': typeof AnunciosAdIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anuncios': typeof AnunciosRouteWithChildren
  '/anuncios/$adId': typeof AnunciosAdIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/anuncios' | '/anuncios/$adId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/anuncios' | '/anuncios/$adId'
  id: '__root__' | '/' | '/anuncios' | '/anuncios/$adId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnunciosRoute: typeof AnunciosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anuncios': {
      id: '/anuncios'
      path: '/anuncios'
      fullPath: '/anuncios'
      preLoaderRoute: typeof AnunciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anuncios/$adId': {
      id: '/anuncios/$adId'
      path: '/$adId'
      fullPath: '/anuncios/$adId'
      preLoaderRoute: typeof AnunciosAdIdRouteImport
      parentRoute: typeof AnunciosRoute
    }
  }
}

interface AnunciosRouteChildren {
  AnunciosAdIdRoute: typeof AnunciosAdIdRoute
}

const AnunciosRouteChildren: AnunciosRouteChildren = {
  AnunciosAdIdRoute: AnunciosAdIdRoute,
}

const AnunciosRouteWithChildren = AnunciosRoute._addFileChildren(
  AnunciosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnunciosRoute: AnunciosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
