/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnunciosRouteImport } from './routes/anuncios'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OfertasRouteImport } from './routes/ofertas'
import { Route as PesquisasRouteImport } from './routes/pesquisas'
import { Route as AnunciosAdIdRouteImport } from './routes/anuncios.$adId'
import { Route as OfertasOfferIdRouteImport } from './routes/ofertas.$offerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnunciosRoute = AnunciosRouteImport.update({
  id: '/anuncios',
  path: '/anuncios',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasRoute = OfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisasRoute = PesquisasRouteImport.update({
  id: '/pesquisas',
  path: '/pesquisas',
  getParentRoute: () => rootRouteImport,
} as any)
const AnunciosAdIdRoute = AnunciosAdIdRouteImport.update({
  id: '/$adId',
  path: '/$adId',
  getParentRoute: () => AnunciosRoute,
} as any)
const OfertasOfferIdRoute = OfertasOfferIdRouteImport.update({
  id: '/$offerId',
  path: '/$offerId',
  getParentRoute: () => OfertasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anuncios': typeof AnunciosRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/ofertas': typeof OfertasRouteWithChildren
  '/pesquisas': typeof PesquisasRoute
  '/anuncios/$adId': typeof AnunciosAdIdRoute
  '/ofertas/$offerId': typeof OfertasOfferIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anuncios': typeof AnunciosRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/ofertas': typeof OfertasRouteWithChildren
  '/pesquisas': typeof PesquisasRoute
  '/anuncios/$adId': typeof AnunciosAdIdRoute
  '/ofertas/$offerId': typeof OfertasOfferIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anuncios': typeof AnunciosRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/ofertas': typeof OfertasRouteWithChildren
  '/pesquisas': typeof PesquisasRoute
  '/anuncios/$adId': typeof AnunciosAdIdRoute
  '/ofertas/$offerId': typeof OfertasOfferIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anuncios'
    | '/cadastro'
    | '/login'
    | '/ofertas'
    | '/pesquisas'
    | '/anuncios/$adId'
    | '/ofertas/$offerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anuncios'
    | '/cadastro'
    | '/login'
    | '/ofertas'
    | '/pesquisas'
    | '/anuncios/$adId'
    | '/ofertas/$offerId'
  id:
    | '__root__'
    | '/'
    | '/anuncios'
    | '/cadastro'
    | '/login'
    | '/ofertas'
    | '/pesquisas'
    | '/anuncios/$adId'
    | '/ofertas/$offerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnunciosRoute: typeof AnunciosRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  OfertasRoute: typeof OfertasRouteWithChildren
  PesquisasRoute: typeof PesquisasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anuncios': {
      id: '/anuncios'
      path: '/anuncios'
      fullPath: '/anuncios'
      preLoaderRoute: typeof AnunciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas': {
      id: '/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof OfertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisas': {
      id: '/pesquisas'
      path: '/pesquisas'
      fullPath: '/pesquisas'
      preLoaderRoute: typeof PesquisasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anuncios/$adId': {
      id: '/anuncios/$adId'
      path: '/$adId'
      fullPath: '/anuncios/$adId'
      preLoaderRoute: typeof AnunciosAdIdRouteImport
      parentRoute: typeof AnunciosRoute
    }
    '/ofertas/$offerId': {
      id: '/ofertas/$offerId'
      path: '/$offerId'
      fullPath: '/ofertas/$offerId'
      preLoaderRoute: typeof OfertasOfferIdRouteImport
      parentRoute: typeof OfertasRoute
    }
  }
}

interface AnunciosRouteChildren {
  AnunciosAdIdRoute: typeof AnunciosAdIdRoute
}

const AnunciosRouteChildren: AnunciosRouteChildren = {
  AnunciosAdIdRoute: AnunciosAdIdRoute,
}

const AnunciosRouteWithChildren = AnunciosRoute._addFileChildren(
  AnunciosRouteChildren,
)

interface OfertasRouteChildren {
  OfertasOfferIdRoute: typeof OfertasOfferIdRoute
}

const OfertasRouteChildren: OfertasRouteChildren = {
  OfertasOfferIdRoute: OfertasOfferIdRoute,
}

const OfertasRouteWithChildren =
  OfertasRoute._addFileChildren(OfertasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnunciosRoute: AnunciosRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  OfertasRoute: OfertasRouteWithChildren,
  PesquisasRoute: PesquisasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
